### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by shellscape** [TheBumpaster/mstdog#14]
Nice little package you have here. I gave it a shot, and it works well for schemas with only `paths`. However, it doesn't consider `subpaths` so more complex models aren't able to be properly faked. Maybe something to take a look at.

**Comment by TheBumpaster** [comment]
Thank you! I have in plan to work a bit more on it this summer. Will close this issue once I push the support for `subpaths`.. 

PS. I avoided `subpaths `intentionally because I have to work that with recursion, but I needed something really quick for e2e tests.
